{ config, pkgs, lib, ... }:

let
  homeDirectory = config.home.homeDirectory;
in {
  # ============================================================================
  # Direnv Configuration
  # ============================================================================
  # Everything related to direnv: program configuration + activation hook
  # ============================================================================

  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # ============================================================================
  # Direnv Activation Hook
  # ============================================================================
  # Generates static direnv hook for performance (avoids dynamic generation)

  home.activation.generateDirenvHook = let
    direnvHookFile = pkgs.writeText "direnv-hook.zsh" ''
      # Static direnv hook - pregenerated by Nix
      _direnv_hook() {
        trap -- "" SIGINT
        eval "$("${pkgs.direnv}/bin/direnv" export zsh)"
        trap - SIGINT
      }
      typeset -ag precmd_functions
      if (( ! ''${precmd_functions[(I)_direnv_hook]} )); then
        precmd_functions=(_direnv_hook $precmd_functions)
      fi
      typeset -ag chpwd_functions
      if (( ! ''${chpwd_functions[(I)_direnv_hook]} )); then
        chpwd_functions=(_direnv_hook $chpwd_functions)
      fi
    '';
  in lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p ${homeDirectory}/.config/zsh
    $DRY_RUN_CMD ln -sf ${direnvHookFile} ${homeDirectory}/.config/zsh/direnv-hook.zsh
  '';
}
