#!/usr/bin/env bash
# Shared Simpsons-themed words for tmux session naming

# All 359 Simpsons-themed words (filtered to 2 words or less)
SIMPSONS_WORDS=(
  "Absotively notarino"
  "Adultivity"
  "Al-kee-hol"
  "America Junior"
  "Anti-booze"
  "Anti-joy ray"
  "Appling"
  "Arm pants"
  "Askaroonie"
  "Assal Horizontology"
  "Avoision"
  "Baby cola"
  "Bagzooka"
  "Banjologist"
  "Bartesque"
  "Barty-come-lately"
  "Basegame"
  "Bathiola"
  "Bazongas"
  "BBBQ"
  "Beer-o"
  "Beer-y"
  "Beginualize"
  "Beginulate"
  "Beheadbumped"
  "Bembarassed"
  "Bemusement Park"
  "Betsy Bleedingheart"
  "Big-boy cup"
  "Bittened"
  "Blim-blam-blame"
  "Blingwad"
  "Blubber-in-law"
  "Blurst"
  "Bolognium"
  "Bonus Eruptus"
  "Boostafazoo"
  "Boo-urns"
  "Bovine University"
  "Brassafrax"
  "Brick-E-Mart"
  "Brownening"
  "Bumbled-bee"
  "Butt-ski"
  "BYOBB"
  "California Cheeseburger"
  "Capdabbler"
  "Car Hole"
  "Chazwazer"
  "Chestal"
  "Chimpan-A"
  "Chocotastic"
  "Christmas bunny"
  "Christmas fairy"
  "Clone-a-saurus"
  "Clouseauesque"
  "Coffee peanuts"
  "Cohuhtage Cheese"
  "Comical book"
  "Comical booklet"
  "Comicdom"
  "Commie-Nazi"
  "Cool juice"
  "Cooking machine"
  "Crantastic"
  "Crap factory"
  "Craptacular"
  "Crayola Oblongata"
  "Crisitunity"
  "Cromulent"
  "Crotch dot"
  "Dash Hole"
  "Debigulator"
  "Deceleratrix"
  "Dickety"
  "Diddly"
  "Disease Box"
  "Doctorb"
  "Dodgerock"
  "Doggie Heaven"
  "Doggie Hell"
  "Dollareydoo"
  "Doobob"
  "Doodily"
  "Dorkus Molorkus"
  "Double-Bacon Geniusburger"
  "Drunkening"
  "Dumbening"
  "Dumpster Buns"
  "Dungeonarium"
  "Dweebazoid"
  "Eddie Punch-clock"
  "Eedily"
  "Elec-trick-city"
  "Electromicide"
  "El Fisa-chiatrist"
  "Embiggen"
  "Esquilax"
  "Evo-lish-us"
  "Fantastipotamus"
  "Farkbot"
  "Fartsy"
  "Fatard"
  "Faxtrola"
  "Femail Carrier"
  "Femailman"
  "Finded"
  "Firehose sweating"
  "Fishbulb"
  "Fishmas"
  "Flander-doodles"
  "Flanswered"
  "Flood pants"
  "Floor Pie"
  "Fluish"
  "Flunjer"
  "Foodbag"
  "Foodrinkery"
  "Fore-snug"
  "Forfty"
  "Forgiveness muscles"
  "Foundling-a-ding"
  "Frinkahedron"
  "Frinkiac 7"
  "Frinkium nitrate"
  "Frogurt"
  "Frost-butt"
  "Fudrucker"
  "Gamblor"
  "Garbagewater"
  "Gibby Gabby"
  "Glavin"
  "Groin-Grabbingly"
  "Gyme"
  "Ham-simple"
  "Headstrongedness"
  "Heckhole"
  "Help-ding"
  "Hey-dilly-ho"
  "Ho-ho-home"
  "Homerhol"
  "Homersexual"
  "Homer Tax"
  "Hoorayvin"
  "Hors Dovers"
  "Hoyvin-Mayvin"
  "Hypohemia"
  "Hungy"
  "Hurricane Vomiting"
  "Hurty"
  "Hydro-animator"
  "Iddly"
  "Imagine friend"
  "Immigant"
  "Introubulate"
  "Italian flapjacks"
  "Japanimation"
  "Jebeditis"
  "Jebus"
  "Jiminy Jillikers"
  "Johnny Come-not-lies"
  "Johnny Lunchpail"
  "Juice Loosener"
  "Jumping Box"
  "Juzz"
  "Kancel"
  "Killbot"
  "Klassic"
  "Knifey Spooney"
  "Knifey Wifey"
  "Knowitallism"
  "Knowledgeum"
  "Kole"
  "Komedy"
  "Krisis"
  "Kwyjibo"
  "Lamarella"
  "Land Cow"
  "Land Monster"
  "Lard-ho"
  "Learnatorium"
  "Learnding"
  "Liberty Log"
  "Little Horse"
  "Lupper"
  "Magumba"
  "Magguppies"
  "Malonga Gilderchuck"
  "Malparkage"
  "Marshed Mallowed"
  "Mazuma"
  "Megacide"
  "Meh"
  "Menapplause"
  "Menu Boy"
  "Merciful Minerva"
  "Microcalifragilistics"
  "Milhousey"
  "Milhousing"
  "Mis-crayola"
  "Mobilomobile"
  "Mom cooties"
  "Money Fight"
  "Moo-moo"
  "Neglecterino"
  "Neighborino"
  "N.E.R.D."
  "Nervous Pervis"
  "No-breath"
  "No-goodnik"
  "Non-Jesus-y"
  "Nose Gravy"
  "Nucleon"
  "Nucular"
  "Nuisancefon"
  "Nulecule"
  "Numbskullery"
  "Nutty Fudgekins"
  "Ny Mets"
  "Okely Dokely"
  "Onetuplet"
  "On-purpose baby"
  "Oodily"
  "Osaka Flu"
  "Ovulicious"
  "Paraplegiarino"
  "Pasghetti"
  "Phalanges crossed"
  "Picto-cube"
  "Pointy kitty"
  "Policey Men"
  "Pollutinest"
  "Popsticle"
  "Posturologist"
  "Pox Box"
  "Presbylutheran"
  "Pretzeled Bread"
  "Pricetaggery"
  "Propity-sition"
  "Protest seizure"
  "Prudissitude"
  "Quantum Tunnel"
  "Quetzalzacatenango"
  "Rastafy"
  "Raytheist"
  "Rear Admiral"
  "Rebigulator"
  "Re-birthday"
  "Re-Christmas"
  "Re-Dorkulated"
  "Re-Neducation"
  "Retirony"
  "Reverse Vampire"
  "Reversifying Glass"
  "Rhinoceros pox"
  "Road model"
  "Sacrilicious"
  "Sally Housecoat"
  "Sausaged"
  "Saxamaphone"
  "Scalpal"
  "Science Pole"
  "Scientician"
  "Scotchtoberfest"
  "Scotsmanwitch"
  "Screamapillar"
  "Scrod Basket"
  "Scuzz-bucket"
  "Senseless Dunderpate"
  "Sentimonies"
  "She. U.I."
  "Shinning"
  "Shirkaday"
  "Shirt-wiener"
  "Sick-E-Mart"
  "Simpson butt"
  "Simpson droppings"
  "Skittlebrau"
  "Smarch"
  "Smashy Smashy"
  "Smendler"
  "Smitily"
  "Smokesperson"
  "Snacktacular"
  "Snitchy"
  "Snow-cop"
  "Snow-girl"
  "Snow-person"
  "Snow wedgie"
  "Snuggle"
  "Snuggle dungeon"
  "Sophistimacated Doowhackey"
  "Special area"
  "Speedhole"
  "Spew-ster"
  "Spiritual De-pantsing"
  "Spokesbaby"
  "Spokesrebel"
  "Squishmas"
  "Squozen"
  "Stabby"
  "Steamed Ham"
  "Sticky-Mart"
  "Stinkables"
  "Successmanship"
  "Suck Shack"
  "Sunblocker"
  "Superliminal"
  "Survive-ded"
  "Suspicious Aloysius"
  "Swedish Lunchbox"
  "Swirly intolerant"
  "Swishifying"
  "Sympathetic barfer"
  "TAKAGI"
  "Tasty-Fake"
  "Taxitude"
  "Telepanhandling"
  "Texas Left"
  "Texas Penny"
  "Throughhole"
  "Tomacco"
  "Tomorry"
  "Ton-In-Law"
  "Topwise"
  "Tracted"
  "Tramampoline"
  "Transulate"
  "Traumedy"
  "Tromboner"
  "Truck-Truck"
  "Truck-Truck-Truck"
  "Twerpsicles"
  "Unblowuppable"
  "Unfaceuptoable"
  "Unky"
  "Un-lame"
  "Unpossible"
  "Un-uncool"
  "Uppity Box"
  "Urination domination"
  "Velocitator"
  "Video dad"
  "Volleybrick"
  "Walking Bird"
  "Wellity"
  "Well-Wisher"
  "White sheep"
  "Whoa Mama"
  "Widget"
  "Wiggle Puppy"
  "Woozle Wuzzle"
  "Word hole"
  "X-mas-licious"
  "Yellow Fatty-Bean"
  "You-know-what-icide"
  "Zazz"
  "Zuh"
)
