set nocompatible

let mapleader=','
imap jk <esc>

set background=dark
colorscheme tokyonight-storm

set shell=zsh " use zsh for :term
set grepprg=rg\ --vimgrep " use ripgrep for :grep

" no swap files or backup files
set noswapfile
set nobackup
set nowritebackup

" allow hidden buffers for easier multi-file editing
set hidden

" detect plugins and indentation per filetype
filetype plugin indent on

" sensible split defaults
set splitbelow
set splitright

" no annoying bells
set noerrorbells
set visualbell

" highlight current line (not supported by alacritty, so need to do here)
set cursorline

" always show at least 1 line above/below cursor
set scrolloff=1

" disable word wrapping
set nowrap
set textwidth=0
set wrapmargin=0
set formatoptions-=t

" ignore case when searching lowercase
set ignorecase
set smartcase

" when a file has changed outside of vim, automatically read it again
set autoread

" always show sign column
set signcolumn=yes

" tame horizontal scroll
set sidescroll=1

" no double spaces after periods when joining lines
set nojoinspaces

" search highlighting off
nmap <silent> <leader><space> :nohlsearch<cr>

" reload current file
nmap <silent> <leader>f :e!<cr>

" comma + enter goes to insert mode
nnoremap ,<cr> A,<cr>

" highlight word without jump in normal mode
nmap <c-w><c-w> :keepjumps normal! mi*`i<cr>

" tame the half-page scroller
nmap <c-d> 5<c-e>5j
vmap <c-d> 5<c-e>5j
nmap <c-u> 5k5<c-y>
vmap <c-u> 5k5<c-y>

" quickfix mappings
nmap <up> :copen<cr>
nmap <down> :cclose<cr>
nmap <left> :cprevious<cr>
nmap <right> :cnext<cr>

" copy relative & absolute paths to system clipboard
nmap <silent> <LEADER>cf :let @+ = expand("%")<CR>
nmap <silent> <LEADER>cF :let @+ = expand("%:p")<CR>

" horizontal center to cursor position
nnoremap <silent> zm zszH

" open terminal at current buffer path
map <C-T> <ESC>:let $BUFPATH=expand('%:p:h')<CR>:terminal<CR>cd $BUFPATH && clear<CR>

" helpful split views
nmap <C-W>} =42>
nmap <C-W>{ =42<
nmap <C-W>O onH{l

" not quite high and low
noremap H 3H
noremap L 3L

" disable fancy cursor
set guicursor=

" vim fugitive mapping
" this has to be done here because plugins are loaded before extraConfig
nmap <leader>b :Buffers<cr>
imap <leader>b <esc>:Buffers<cr>
vmap <leader>b <esc>:Buffers<cr>

function! OpenInGitHub()
	let l:remote = system('git remote get-url origin')
	let l:repo = substitute(l:remote, '.*github.com[:/]', '', '')
	let l:repo = substitute(l:repo, '.git$', '', '')
	let l:branch = system('git rev-parse --abbrev-ref HEAD')
	let l:path = expand('%')
	let l:line = line('.')
	let l:url = printf('https://github.com/%s/blob/%s/%s#L%s', l:repo, l:branch, l:path, l:line)
	execute 'silent !open ' . shellescape(l:url)
endfunction

nnoremap <leader>gh :call OpenInGitHub()<CR>

" RestoreCursor restores the last cursor position.
function! RestoreCursor()
		if line("\"") <= line("$")
				normal! g`"
				return 1
		endif
endfunction

augroup config
	autocmd!

	" jump to last cursor position on file load
	autocmd BufWinEnter * silent! call RestoreCursor()

	" force quickfix to always open full width
	autocmd FileType qf wincmd J
augroup end
